id: A47930F73
title: f674F
type: translation
source_metadata:
  languages:
  - sa
  - bo
  - de
  datatype: PlainText
  created_at: 2022-05-27 14:54:26.527042
  last_modified_at: 2022-05-27 14:54:26.527049
